In [12]:
import numpy as np

In [13]:
mat1 = np.array([[1, 2], [1, 3]])
mat1

array([[1, 2],
       [1, 3]])

In [14]:
mat2 = mat1 @ mat1
mat2

array([[ 3,  8],
       [ 4, 11]])

In [15]:
mat3 = np.linalg.inv(mat2)
mat3

array([[11., -8.],
       [-4.,  3.]])

In [16]:
mat3 @ mat2

array([[1., 0.],
       [0., 1.]])

In [22]:
np.linalg.inv(np.array([[3, -3],[4, -5]])) @ np.array([[3],[2]])

array([[3.],
       [2.]])

In [19]:
np.array([[1, 1],[-2, 1]]) @ np.array([[-3],[12]])

array([[ 9],
       [18]])